<header>
    HEADER
    <nav>
        <ul>
            <li>nav1</li>
            <li>nav2</li>
            <li>nav3</li>
            <li>nav4</li>
            <li>nav5</li>
        </ul>
    </nav>
</header>